name: cd

on: [push, pull_request]

jobs:
  screenshot:
    name: screenshot sketches 📸
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: actions/cache@v2
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}

      - uses: technote-space/get-diff-action@v4
        with:
          PATTERNS: |
            content/sketches/*
          FORMAT: json

      - name: Setup node env
        uses: actions/setup-node@v2.1.2
        with:
          node-version: 12.x

      - name: yarn install
        run: yarn

      - name: echo changed files
        run: echo '${{ env.GIT_DIFF_FILTERED }}' | jq . | yarn generate-caps
